version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: aiqdatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - aiqvolume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  aiqvolume:
